FROM node:22.13.1

ENV NODE_ENV=development

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update -yqq \
    && apt-get -yqq install nasm

RUN npm install -g pnpm@9.14.4 --silent

COPY ./package.json .

RUN pnpm install -q

CMD [ "pnpm", "run", "dev" ]
