FROM node:18.12.0

ENV NODE_ENV=development

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update -yqq \
    && apt-get -yqq install nasm

COPY ./package.json .

RUN npm install -q

CMD [ "npm", "run", "dev" ]
